### DISCUSSION TITLE
Laravel Presets, WebSocket && Queue

### DISCUSSION THREAD

**Discussion by devajmeireles** [kool-dev/kool#368] [Q&A] [answered]
Olá!

Primeiramente gostaria de agradecer o trabalho de vocês com o desenvolvimento do Kool.

Bom, sou desenvolvedor Laravel e gostaria de utilizar o Kool para gerenciar o meu ambiente de trabalho. Entretanto estudando a documentação dele, me surgiu algumas dúvidas que gostaria de saná-las:

Dúvidas:
1. Como eu poderia fazer para iniciar um servidor websocket do Laravel usando o Kool? Atualmente usando o Docker, eu compilei uma imagem contendo o "Supervisor" para que ele inicie um processo do WebSocket (porta 6001).

2. Como eu poderia fazer para lidar com filas do Laravel usando o Kool? Atualmente usando o Docker, eu compilei uma imagem contendo o "Supervisor" para que ele inicie e gerencie as filas.

Muito obrigado desde já!

---

Hi!

 First of all I would like to thank to the Kool team for your work with the development of Kool.

 Well, I'm a Laravel developer and I would like to use Kool to manage my desktop application enviroment. However, studying his documentation, I had some doubts that I would like to resolve:

 Doubts:
 1. How could I start a Laravel websocket server using Kool?  Currently using Docker, I've compiled an image containing "Supervisor" so that it starts a WebSocket process (port 6001).

 2. How could I handle Laravel queues using Kool?  Currently using Docker, I've compiled an image containing the "Supervisor" for it to start and manage the queues.

 Thank you very much!

**Comment by danielsuguimoto** [comment, marked as answer]
Olá @ajmeireles! Agradecemos muito seu interesse no kool! Você pode adicionar mais dois novos serviços no `docker-compose.yml`, ambos baseados no container que roda a sua aplicação.

A seguir, um exemplo do socket:

```yml
socket:
    image: NOME_DO_CONTAINER_DA_SUA_APPLICACAO
    command: ["php", "artisan", "websockets:serve"]
    ports:
     - "${KOOL_SOCKET_PORT:-6001}:6001"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
     - .:/app:delegated
    networks:
      - kool_local
      - kool_global
```

Para as filas, a ideia seria algo parecido, porém ao invés do comando `websocket:serve`, seria `queue:listen`...e não haverá a necessidade de expôr a porta...

---

You can add two services to your `docker-compose.yml` file, both of them based on your application container.

Websocket example:

```yml
socket:
    image: YOUR_APP_SERVICE_NAME (e.g.: my-project_app)
    command: ["php", "artisan", "websockets:serve"]
    ports:
     - "${KOOL_SOCKET_PORT:-6001}:6001"
    environment:
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
     - .:/app:delegated
    networks:
      - kool_local
      - kool_global
```

About the jobs queue, the idea is basically the same, but the command is `queue:listen` and I guess there is no need to expose the ports.
