### DISCUSSION TITLE
Support for Spring boot (java based system)

### DISCUSSION THREAD

**Discussion by hariohmprasath** [kool-dev/kool#399] [Ideas]
**Describe the feature**

A clear and concise description of what the feature idea is. Please make sure you didn't find an existing issue with the same subject.

Spring boot is one of the heavily used containerized environment when it comes to java, it would be great to have this support added to this platform. The whole build and packing can be done in a build container so the developer can just concentrate on write code, instead of worrying about the build & deployment platform.

I will be happy to contribute this, let me know if the team is interested in bring this support to platform

**Backward compatibility concerns**

Would this be BC? 
No

**Use cases**

Springboot (java based environment)

**Examples**

Microservices & applications built using Spring boot

**Comment by fbrissi** [comment]
A spring-boot preset would be great.
It's something we already thought we started looking at this with a docker image for the kool.

You can by taking a look at it, it's still a start.

https://github.com/kool-dev/docker-java

Start with Spring-boot in https://start.spring.io with Java 8, gradle or maven and Spring-boot 2.4.8 because the new Spring version needs Gradle 6.8.x, 6.9.x or 7.x, we need to update that in this image and teste with more use case, and with Spring Web.

We still don't have a preset that creates the project but I think we can have it using our own API.

Example:
https://start.spring.io/starter.zip?type=gradle-project&language=java&bootVersion=2.4.8.RELEASE&baseDir=demo&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&packaging=jar&javaVersion=1.8&dependencies=web

### Create the files:
docker-compose.yml

```yml
version: '3'
services:
  app:
    image: kooldev/java:8
    ports:
      - "${KOOL_HTTP_PORT:-80}:8080"
    environment:
      MAIN_CLASS: "com.example.demo.DemoApplication"
      ASUSER: "${KOOL_ASUSER:-0}"
      UID: "${UID:-0}"
    volumes:
      - .:/app:delegated
    networks:
      - kool_local
      - kool_global

networks:
  kool_local:
  kool_global:
    external: true
    name: "${KOOL_GLOBAL_NETWORK:-kool_global}"
```

kool.yml
```yml
scripts:
  mvn: kool docker kooldev/java:8 mvn
  gradle: kool docker kooldev/java:8 gradle
  jshell: kool docker kooldev/java:11 jshell
```

And execute:

```sh
kool run gradle build # gradle
kool run mvn package # maven
kool start
```
