### ISSUE TITLE
kool.yml include other files

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#1]
Our file can get big quickly, let's add a simple way of including other files and merging all data, for example:

### kool.yml

```yaml
includes:
  - kool.qa.yml

scripts:
  php: kool exec app php
  composer: kool exec app composer

  node: kool docker fireworkweb/node:14 node
  yarn: kool docker fireworkweb/node:14 yarn

  install:
    - kool start
    - cp .env.example .env
    - kool run composer install
    - kool run php artisan key:generate
    - kool run yarn install
    - kool run yarn run dev

  reset:
    - kool run composer install
    - kool run php artisan migrate:fresh --seed
    - kool run yarn install
    - kool run yarn run dev
```

### kool.qa.yml

```yaml
includes:
  - kool.qa.yml

scripts:
  phpqa: kool docker jakzal/phpqa:1.34-alpine
  nodeqa: kool docker fireworkweb/node:14-qa

  # temp?
  wait-services: kool exec app dockerize -wait tcp://database:3306 -wait tcp://cache:6379 -timeout 30s

  # useful for ci/cd
  eslint: kool run nodeqa eslint --ext vue,js .
  phan: kool run phpqa phan --color -p -l app -iy 5
  phpcpd: kool run phpqa phpcpd --fuzzy app
  phpmd: kool run phpqa phpmd app text phpmd/codesize.xml,phpmd/controversial.xml,phpmd/design.xml,phpmd/naming.xml,unusedcode,phpmd/cleancode.xml
  phpmnd: kool run phpqa phpmnd app --ignore-funcs=round,sleep,abort,strpad,number_format --exclude=tests --progress --extensions=default_parameter,-return,argument
  phpstan: kool run phpqa phpstan app
  php-security-checker: kool run phpqa security-checker security:check composer.lock
  psalm: kool run phpqa psalm
  rector: kool run phpqa rector process . --set laravel60 --dry-run
  php-cs-fixer:
    - kool run phpqa php-cs-fixer fix app --dry-run --diff
    - kool run phpqa php-cs-fixer fix config --dry-run --diff
    - kool run phpqa php-cs-fixer fix database --dry-run --diff
    - kool run phpqa php-cs-fixer fix tests --dry-run --diff
```
