### ISSUE TITLE
Problems with the $HOME variable

### ISSUE THREAD

**Issue by diegohcosta** [kool-dev/kool#100]
I'm having problems with the $HOME variable,
Running the command: kool run composer install with the $HOME variable in docker-composer.yml does not work,
We create it in the .ENV file and assign the value to it, even so it doesn't work, but if we leave 'hardcoded' the $HOME variable path, for example: /home/user/.ssh:/home/kool/.ssh:delegated in volumes, it works.

**Comment by fabriciojs** [comment]
Thanks for the report!

To first of all assess this we should:

- Add this variable to an include-list so we can debug it on `kool info` (currently not showing). Maybe we could add a `--dump-env=<env var name>`  option, so then we simply dump the value of such environment variable for debugging purposes.

- Review and add tests for its definition if possible (not-set, and overriding with previously defined env).

**Comment by danielsuguimoto** [comment]
@diegohcosta @fabriciojs actually, `kool info` has `KOOL_` as default filter. If you run `kool info HOME`, the `$HOME` variable shows up, if it is set.

**Comment by diegohcosta** [comment]
When outputting the code: kool info HOME, return me:
HOME = / home / firework
PROFILEHOME =

**Comment by dbpolito** [comment]
@diegohcosta 

please share with us:

```
docker info
docker-compose --version
```

**Comment by dbpolito** [comment]
Also:

```
docker-compose config
```

**Comment by dbpolito** [comment]
And also share:

```
env | grep HOME
set | grep HOME
```

I think i may have found the culprit:

https://forums.docker.com/t/docker-compose-not-seeing-environment-variables-on-the-host/11837/3

On his bash HOME may not be exported by default, i think we can just inject `HOME` by default and fix this problem, it won't work by default directly with `docker-compose` on some envs but that's ok.

**Comment by diegohcosta** [comment]
@dbpolito 

```docker-compose config:```
```
networks:
  kool_global:
    external: true
    name: kool_global
  kool_local: {}
services:
  app:
    environment:
      ASUSER: '0'
      UID: '0'
    image: kooldev/php:7.4-nginx
    networks:
      kool_global: null
      kool_local: null
    ports:
    - published: 80
      target: 80
    volumes:
    - /home/firework/Projetos/erp:/app:delegated
    - /home/firework/snap/docker/471/.ssh:/home/kool/.ssh:delegated
  cache:
    image: redis:6-alpine
    networks:
      kool_local: null
    volumes:
    - cache:/data:delegated
  database:
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: '"docker"'
      MYSQL_PASSWORD: '"secret"'
      MYSQL_ROOT_PASSWORD: '"secret"'
      MYSQL_USER: '"docker"'
    image: mysql:8.0
    networks:
      kool_local: null
    ports:
    - published: 3306
      target: 3306
    volumes:
    - db:/var/lib/mysql:delegated
version: '3.7'
volumes:
  cache: {}
  db: {}
```
