### ISSUE TITLE
TTY Not Detected stdin

### ISSUE THREAD

**Issue by fbrissi** [kool-dev/kool#159]
**Describe the bug**

It looks like TTY is not identified with stdin.

**Kool version and environment**

```
C:\Workspace\mega-bilheteria\portal-api>kool info
KOOL_ASUSER=0
KOOL_GLOBAL_NETWORK=kool_global
KOOL_NAME=portal-api
KOOL_VERBOSE=1

C:\Workspace\mega-bilheteria\portal-api>kool --version
kool version 1.4.0
```

**To Reproduce**

kool.yml

```
scripts:
  pg_restore : kool exec -e PGPASSWORD=$DB_PASSWORD database pg_restore -U $DB_USERNAME --dbname=$DB_DATABASE --verbose
```

Execute command:

`kool run pg_restore < C:\Workspace\file-dump.tar`

**Expected behavior**

Execute the pg_restore with a dump file.

**Screenshots**

![image](https://user-images.githubusercontent.com/339706/95664297-ccece880-0b1c-11eb-813f-339606f0cae5.png)

**Comment by fabriciojs** [comment]
@fbrissi thanks for the report! we will look into this.

Meanwhile, a quick work around would be: if you define the input file redirection ` < ` within your `kool.yml` file that should work as kool itself will handle the input:

```yml
scripts:
  pg_restore : kool exec -e PGPASSWORD=$DB_PASSWORD database pg_restore -U $DB_USERNAME --dbname=$DB_DATABASE --verbose
  pg_restore_file: kool run pg_restore < path\to\file.tar
```

Something like this.
