### ISSUE TITLE
Refactor preset options for array instead of key/value object

### ISSUE THREAD

**Issue by fabriciojs** [kool-dev/kool#217]
for the sake of clarity and future extendability maybe we might change the format of this `options:` entry from the current object to an array like:

```yml
  options:
    - name: MySQL 8.0
      template: mysql8
    - name: PostgreSQL 13
      template: postgresql13
```

We could do this in a future iteration as well - the goal being to  make clear the importance of the key (template name) on these options setting. Having an array of objects like this could possibly help I guess.

_Originally posted by @fabriciojs in https://github.com/kool-dev/kool/pull/209#discussion_r539521184_
