### ISSUE TITLE
Comments are Not Included in the Generated Preset Yaml Files

### ISSUE THREAD

**Issue by indiegenus** [kool-dev/kool#315]
**Describe the bug**

If you add a comment to a Preset `/templates` file, the comment is **not** included in the auto-generated Yaml file when running `kool preset`.

In the example below, the comment `# - add more setup commands` is not included, and the `kool.yml` file is created with `setup: kool start`, instead of a multi-line script with a commented out command in the list.

This template file:

```yaml
# /templates/scripts/php.yml
scripts:
  php: kool exec app php

  setup:
    - kool start
    # - add more setup commands
```

Creates this `kool.yml`:

```yaml
scripts:
  composer: kool exec app composer
  php: kool exec app php
  setup: kool start
```

**Kool version and environment**

Kool 1.11.0
Linux (Linux Mint 20 - Ubuntu 20.04)

**To Reproduce**

**Expected behavior**

```yaml
scripts:
  composer: kool exec app composer
  php: kool exec app php
  setup:
    - kool start
    # - add more setup commands
```
