### ISSUE TITLE
Instalação do ioncube_loader

### ISSUE THREAD

**Issue by alienwebvision** [kool-dev/kool#385]
Boa noite!
Primeiramente gostaria de parabenizar pelo projeto!
Gostaria de solicitar a instalação do ioncube_loader, ou uma orientação para adicionar a extensão.
Obrigado!

**Comment by danielsuguimoto** [comment]
@alienwebvision por enquanto você pode criar um `Dockerfile` para extender qualquer uma de nossas imagens. Aí no `docker-compose.yml`, ao invés de usar a imagem, usaria o seu `Dockerfile` pra buildar o serviço da sua aplicação.

## Dockerfile
```dockerfile
FROM kooldev/php:7.4-nginx

RUN [comandos para instalar e habilitar a extensão]
```

## docker-compose.yml
```yml
services:
  app:
    build: . # Caso Dockerfile esteja em outra pasta, use ./caminho_da_pasta
```
