### ISSUE TITLE
Create GH Action on Marketplace

### ISSUE THREAD

**Issue by dbpolito** [kool-dev/kool#73]
Currently we're using kool in some projects usinig default GH Action and downloading kool:

```
env:
  KOOL_TTY_DISABLE: 1

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: kool install
        run: sudo curl -L https://github.com/kool-dev/kool/releases/download/1.0.6/kool-linux-amd64 -o /usr/local/bin/kool && sudo chmod +x /usr/local/bin/kool

      - name: kool lint
        run: kool run lint
```

Let's create an action and publish at https://github.com/marketplace so we can simplify this to something like:

```
jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: kool-dev/kool@v1
        name: kool lint
        run: kool run lint
```
